# fly.toml app configuration file generated for express-web-app-template on 2023-11-07T10:18:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "express-web-app-template"
primary_region = "den"

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
