name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'typescript-template'
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'reidfluegel'
          POSTGRES_PASSWORD: 'asd'
          POSTGRES_DB: 'post'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for src changes
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | \
            { grep -q 'src/' || \
              grep -q 'package-lock.json' || \
              grep -q 'babel.config.js' || \
              grep -q 'Dockerfile' || \
              grep -q 'fly.toml' || \
              grep -q 'tsconfig.json' || \
              grep -q 'webpack.config.js'; }; then
          echo "PROD_CHANGED=true" >> $GITHUB_ENV
          echo "::set-output name=PROD_CHANGED::true"
          else
          echo "PROD_CHANGED=false" >> $GITHUB_ENV
          echo "::set-output name=PROD_CHANGED::false"
          fi
        continue-on-error: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        # runs "npm i" as well
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Run Backend Tests (Development)
        run: npm run test:github backend

      - name: Run Frontend Tests (Development)
        run: npm run test:github frontend

      - name: Run e2e Tests (Development)
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: |
            AUTH0_SECRET=$AUTH0_SECRET
            npm run backend
            npm run frontend

      - name: Install Flyctl
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build Frontend
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        run: npm run build:staging

      - name: Deploy to Staging with Fly
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME

      - name: Run Blackbox Tests (Staging)
        run: npm run test:staging

      - name: Run e2e Tests (Staging)
        run: npm run e2e:staging
