name: Deploy to Staging

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'typescript-template'
    timeout-minutes: 10

    steps:
      - name: Install Flyctl
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build Frontend
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        run: npm run build:staging

      - name: Deploy to Staging with Fly
        if: success() && steps.check_changes.outputs.PROD_CHANGED == 'true'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME

      - name: Run Blackbox Tests (Staging)
        run: npm run test:staging

      - name: Run e2e Tests (Staging)
        run: npm run e2e:staging
