name: Deploy to Staging

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'express-web-app-template'
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build Frontend
        run: npm run build:staging

      - name: Deploy to Staging with Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME
