name: Run Tests on Push to Main

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'some_value'
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'reidfluegel'
          POSTGRES_PASSWORD: 'asd'
          POSTGRES_DB: 'post'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        # runs "npm i" as well
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Run Backend Tests
        run: npm run test:github backend

      - name: Run Frontend Tests
        run: npm run test:github frontend

      - name: Run e2e Test
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: |
            npm run backend
            npm run frontend

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Staging with Fly
        if: success()
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy -a $APP_NAME
