name: Update NPM Dependencies and Test

on:
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM
  workflow_dispatch: # Manual trigger

jobs:
  update-and-test:
    runs-on: ubuntu-latest
    env:
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      AUTH0_PASSWORD: ${{ secrets.AUTH0_PASSWORD }}
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'reidfluegel'
          POSTGRES_PASSWORD: 'asd'
          POSTGRES_DB: 'post'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        # runs "npm i" as well
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Update NPM packages
        run: npm update

      - name: Run Backend Tests
        run: npm run test:github backend

      - name: Run Frontend Tests
        run: npm run test:github frontend

      - name: Run e2e Test
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: |
            npm run backend
            npm run frontend

      - name: Create PR if Tests Pass
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          branch_name="automated/update-dependencies-$(date +%s)"
          git checkout -b $branch_name
          git add package-lock.json package.json
          # Check if there are any changes to commit in package.json
          if git diff --exit-code --cached --name-only | grep -q 'package-lock.json'; then
            echo "Changes found in package.json, creating PR."
            git commit -m "Update NPM dependencies"
            git push origin $branch_name
            gh pr create --title "Update NPM Dependencies" --body "Automatic PR to update dependencies."
          else
            echo "No changes to package.json, skipping PR creation."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
