name: Update NPM Dependencies and Test

on:
  schedule:
    - cron: '0 3 * * *' # Run daily at 3 AM
  workflow_dispatch: # Manual trigger

jobs:
  update-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: 'reidfluegel'
          POSTGRES_PASSWORD: 'asd'
          POSTGRES_DB: 'post'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Update NPM packages
        run: npm update

      - name: Run Tests
        run: npm run test

      - name: Update NPM packages and create PR if needed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          branch_name="automated/update-dependencies"

          # Check if there are changes
          git diff --exit-code || git diff --staged --exit-code
          if [ $? -ne 0 ]; then
            # Check if branch already exists
            git fetch origin $branch_name
            if git show-ref --quiet refs/remotes/origin/$branch_name; then
              echo "Branch already exists, deleting it."
              # Close associated PR
              gh pr close --delete-branch --repo ${{ github.repository }} $branch_name || true
              # Delete remote branch
              git push origin --delete $branch_name || true
            fi

            # Create new branch
            git checkout -b $branch_name
            git add package-lock.json package.json
            git commit -m "Update NPM dependencies"
            git push origin $branch_name
            gh pr create --title "Update NPM Dependencies" --body "Automatic PR to update dependencies."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

